steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/nodejs-wa-chatbot/nodejs-wa-chatbot:v1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/github_brian02oriel_nodejs-wa-chatbot/nodejs-wa-chatbot:v1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --location=us-central1
  - --cluster=gkecluster